name: Release
on:
  push:
    branches:
      - master
jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-docker-buildx@v1.0.5
      - uses: actions/checkout@v2
      - run: docker login -u jwalton9 -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 --push -t jwalton9/joewalton.me .
